/*
 * Copyright (c) 2018 Boris Fox, REDCOM-Internet CJSC
 * All rights reserved.
 */

package ru.redcom.software.util.integration.api.client.dadata.IntegrationTests;

import org.hamcrest.Matcher;
import org.springframework.http.HttpStatus;
import ru.redcom.software.util.integration.api.client.dadata.DaDataClientException;
import ru.redcom.software.util.integration.api.client.dadata.dto.APIErrorMessage;

import java.util.function.Function;

import static org.hamcrest.Matchers.*;
import static ru.redcom.software.util.integration.api.client.dadata.APIErrorCode.BAD_REQUEST_FORMAT;

public class TestCasesError {
	public enum SampleErrorAddresses {
		EMPTY_ARRAY(new String[0],
		            "[]",
		            "Incorrect request format or data type",
		            HttpStatus.BAD_REQUEST, "{\"detail\":\"Bad request. Use non empty list.\"}",
		            TestCasesError::matcherEmptyArray);
/*
		KHABAROVSK_2("680030, Россия, Хабаровский край, г.Хабаровск, ул.Гамарника,64, кв.101",
		             "[{\"source\":\"680030, Россия, Хабаровский край, г.Хабаровск, ул.Гамарника,64, кв.101\",\"result\":\"г Хабаровск, ул Гамарника, д 64, кв 101\",\"postal_code\":\"680030\",\"country\":\"Россия\",\"region_fias_id\":\"7d468b39-1afa-41ec-8c4f-97a8603cb3d4\",\"region_kladr_id\":\"2700000000000\",\"region_with_type\":\"Хабаровский край\",\"region_type\":\"край\",\"region_type_full\":\"край\",\"region\":\"Хабаровский\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":\"a4859da8-9977-4b62-8436-4e1b98c5d13f\",\"city_kladr_id\":\"2700000100000\",\"city_with_type\":\"г Хабаровск\",\"city_type\":\"г\",\"city_type_full\":\"город\",\"city\":\"Хабаровск\",\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":\"р-н Индустриальный\",\"city_district_type\":\"р-н\",\"city_district_type_full\":\"район\",\"city_district\":\"Индустриальный\",\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":\"27392ccb-9a42-48aa-99b0-a5e5b314700b\",\"street_kladr_id\":\"27000001000017100\",\"street_with_type\":\"ул Гамарника\",\"street_type\":\"ул\",\"street_type_full\":\"улица\",\"street\":\"Гамарника\",\"house_fias_id\":\"aa68fa2b-acbd-4b3f-a525-d06e0462ccc6\",\"house_kladr_id\":\"2700000100001710014\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"64\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":\"кв\",\"flat_type_full\":\"квартира\",\"flat\":\"101\",\"flat_area\":\"75.7\",\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"aa68fa2b-acbd-4b3f-a525-d06e0462ccc6\",\"fias_code\":\"27000001000000001710014\",\"fias_level\":\"8\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"2700000100001710014\",\"capital_marker\":\"2\",\"okato\":\"08401365000\",\"oktmo\":\"08701000\",\"tax_office\":\"2723\",\"tax_office_legal\":\"2723\",\"timezone\":\"UTC+10\",\"geo_lat\":\"48.4745069\",\"geo_lon\":\"135.0847765\",\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":0,\"qc_complete\":0,\"qc_house\":2,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		             TestCasesError::matcherKhabarovsk2),
		KHABAR_CITYAREA_1("г.Хабаровск, пос.Берёзовка, ул.Ванинская, д.10, кв.3",
		                  "[{\"source\":\"г.Хабаровск, пос.Берёзовка, ул.Ванинская, д.10, кв.3\",\"result\":\"г Хабаровск, пгт Березовка, ул Ванинская, д 10, кв 3\",\"postal_code\":\"680025\",\"country\":\"Россия\",\"region_fias_id\":\"7d468b39-1afa-41ec-8c4f-97a8603cb3d4\",\"region_kladr_id\":\"2700000000000\",\"region_with_type\":\"Хабаровский край\",\"region_type\":\"край\",\"region_type_full\":\"край\",\"region\":\"Хабаровский\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":\"a4859da8-9977-4b62-8436-4e1b98c5d13f\",\"city_kladr_id\":\"2700000100000\",\"city_with_type\":\"г Хабаровск\",\"city_type\":\"г\",\"city_type_full\":\"город\",\"city\":\"Хабаровск\",\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":\"р-н Краснофлотский\",\"city_district_type\":\"р-н\",\"city_district_type_full\":\"район\",\"city_district\":\"Краснофлотский\",\"settlement_fias_id\":\"24a1f96f-0a75-48d7-adaa-03a1aea75bc7\",\"settlement_kladr_id\":\"2700000100300\",\"settlement_with_type\":\"пгт Березовка\",\"settlement_type\":\"пгт\",\"settlement_type_full\":\"поселок городского типа\",\"settlement\":\"Березовка\",\"street_fias_id\":\"94c61c6f-d2a9-46ad-aa44-ef1f299681b3\",\"street_kladr_id\":\"27000001003003199\",\"street_with_type\":\"ул Ванинская\",\"street_type\":\"ул\",\"street_type_full\":\"улица\",\"street\":\"Ванинская\",\"house_fias_id\":null,\"house_kladr_id\":null,\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"10\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":\"кв\",\"flat_type_full\":\"квартира\",\"flat\":\"3\",\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"94c61c6f-d2a9-46ad-aa44-ef1f299681b3\",\"fias_code\":\"27000001003000000310000\",\"fias_level\":\"7\",\"fias_actuality_state\":\"99\",\"kladr_id\":\"27000001003003199\",\"capital_marker\":\"2\",\"okato\":\"08401371000\",\"oktmo\":\"08701000\",\"tax_office\":\"2722\",\"tax_office_legal\":\"2722\",\"timezone\":\"UTC+10\",\"geo_lat\":\"48.5554327\",\"geo_lon\":\"135.1233954\",\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":0,\"qc_complete\":10,\"qc_house\":10,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		                  TestCasesError::matcherKhabarCityArea1),
		KHABAR_CITYAREA_2("г.Хабаровск, пос.Берёзовка, квартал Мира, 9, кв.5",
		                  "[{\"source\":\"г.Хабаровск, пос.Берёзовка, квартал Мира, 9, кв.5\",\"result\":\"г Хабаровск, пгт Березовка, кв-л Мира, д 9, кв 5\",\"postal_code\":\"680025\",\"country\":\"Россия\",\"region_fias_id\":\"7d468b39-1afa-41ec-8c4f-97a8603cb3d4\",\"region_kladr_id\":\"2700000000000\",\"region_with_type\":\"Хабаровский край\",\"region_type\":\"край\",\"region_type_full\":\"край\",\"region\":\"Хабаровский\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":\"a4859da8-9977-4b62-8436-4e1b98c5d13f\",\"city_kladr_id\":\"2700000100000\",\"city_with_type\":\"г Хабаровск\",\"city_type\":\"г\",\"city_type_full\":\"город\",\"city\":\"Хабаровск\",\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":\"р-н Краснофлотский\",\"city_district_type\":\"р-н\",\"city_district_type_full\":\"район\",\"city_district\":\"Краснофлотский\",\"settlement_fias_id\":\"24a1f96f-0a75-48d7-adaa-03a1aea75bc7\",\"settlement_kladr_id\":\"2700000100300\",\"settlement_with_type\":\"пгт Березовка\",\"settlement_type\":\"пгт\",\"settlement_type_full\":\"поселок городского типа\",\"settlement\":\"Березовка\",\"street_fias_id\":\"d36a168f-7cd5-4de4-be34-857144885a44\",\"street_kladr_id\":\"27000001003000500\",\"street_with_type\":\"кв-л Мира\",\"street_type\":\"кв-л\",\"street_type_full\":\"квартал\",\"street\":\"Мира\",\"house_fias_id\":\"a8a19637-2606-4e67-94d2-41e08e809559\",\"house_kladr_id\":\"2700000100300050001\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"9\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":\"кв\",\"flat_type_full\":\"квартира\",\"flat\":\"5\",\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"a8a19637-2606-4e67-94d2-41e08e809559\",\"fias_code\":\"27000001003000000050001\",\"fias_level\":\"8\",\"fias_actuality_state\":\"99\",\"kladr_id\":\"2700000100300050001\",\"capital_marker\":\"2\",\"okato\":\"08401371000\",\"oktmo\":\"08701000\",\"tax_office\":\"2722\",\"tax_office_legal\":\"2722\",\"timezone\":\"UTC+10\",\"geo_lat\":\"48.5576507\",\"geo_lon\":\"135.1191621\",\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":0,\"qc_complete\":0,\"qc_house\":2,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		                  TestCasesError::matcherKhabarCityArea2),
		KHABAR_SETTLEMENT_1("Хабаровский район, с.Князе-Волконское, Базовый проезд, д.1",
		                    "[{\"source\":\"Хабаровский район, с.Князе-Волконское, Базовый проезд, д.1\",\"result\":\"Хабаровский край, Хабаровский р-н, с Князе-Волконское, проезд Базовый, д 1\",\"postal_code\":\"680551\",\"country\":\"Россия\",\"region_fias_id\":\"7d468b39-1afa-41ec-8c4f-97a8603cb3d4\",\"region_kladr_id\":\"2700000000000\",\"region_with_type\":\"Хабаровский край\",\"region_type\":\"край\",\"region_type_full\":\"край\",\"region\":\"Хабаровский\",\"area_fias_id\":\"11d90802-ea26-4780-ae59-8c4726d6319f\",\"area_kladr_id\":\"2701800000000\",\"area_with_type\":\"Хабаровский р-н\",\"area_type\":\"р-н\",\"area_type_full\":\"район\",\"area\":\"Хабаровский\",\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":\"9d7ee321-72e0-401b-a196-a2f5c0702901\",\"settlement_kladr_id\":\"2701800002600\",\"settlement_with_type\":\"с Князе-Волконское\",\"settlement_type\":\"с\",\"settlement_type_full\":\"село\",\"settlement\":\"Князе-Волконское\",\"street_fias_id\":\"19829db1-ec8a-47f5-b88e-8c4ba3d87aeb\",\"street_kladr_id\":\"27018000026002900\",\"street_with_type\":\"проезд Базовый\",\"street_type\":\"проезд\",\"street_type_full\":\"проезд\",\"street\":\"Базовый\",\"house_fias_id\":null,\"house_kladr_id\":null,\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"1\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"19829db1-ec8a-47f5-b88e-8c4ba3d87aeb\",\"fias_code\":\"27018000026000000290000\",\"fias_level\":\"7\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"27018000026002900\",\"capital_marker\":\"4\",\"okato\":\"08255000029\",\"oktmo\":\"08655425\",\"tax_office\":\"2720\",\"tax_office_legal\":\"2720\",\"timezone\":\"UTC+10\",\"geo_lat\":\"48.4890831\",\"geo_lon\":\"135.4613803\",\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":3,\"qc_complete\":10,\"qc_house\":10,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		                    TestCasesError::matcherKhabarSettlement1),
		KHABAR_SETTLEMENT_2("пер. Советский, 3, с. Чумикан, 682560",
		                    "[{\"source\":\"пер. Советский, 3, с. Чумикан, 682560\",\"result\":\"Хабаровский край, с Чумикан, пер Советский, д 3\",\"postal_code\":\"682560\",\"country\":\"Россия\",\"region_fias_id\":\"7d468b39-1afa-41ec-8c4f-97a8603cb3d4\",\"region_kladr_id\":\"2700000000000\",\"region_with_type\":\"Хабаровский край\",\"region_type\":\"край\",\"region_type_full\":\"край\",\"region\":\"Хабаровский\",\"area_fias_id\":\"1e57a568-7eca-4747-878c-c6d4e27f96d7\",\"area_kladr_id\":\"2701600000000\",\"area_with_type\":\"Тугуро-Чумиканский р-н\",\"area_type\":\"р-н\",\"area_type_full\":\"район\",\"area\":\"Тугуро-Чумиканский\",\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":\"70122a59-d274-473c-9817-e8f349075653\",\"settlement_kladr_id\":\"2701600000100\",\"settlement_with_type\":\"с Чумикан\",\"settlement_type\":\"с\",\"settlement_type_full\":\"село\",\"settlement\":\"Чумикан\",\"street_fias_id\":\"0bb9ae71-8d9e-4c93-b445-98b1805c28f8\",\"street_kladr_id\":\"27016000001001300\",\"street_with_type\":\"пер Советский\",\"street_type\":\"пер\",\"street_type_full\":\"переулок\",\"street\":\"Советский\",\"house_fias_id\":\"e691fdd6-cce2-4b50-b671-11007c5923a6\",\"house_kladr_id\":\"2701600000100130001\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"3\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"e691fdd6-cce2-4b50-b671-11007c5923a6\",\"fias_code\":\"27016000001000000130001\",\"fias_level\":\"8\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"2701600000100130001\",\"capital_marker\":\"1\",\"okato\":\"08246000001\",\"oktmo\":\"08646411\",\"tax_office\":\"2720\",\"tax_office_legal\":\"2720\",\"timezone\":\"UTC+10\",\"geo_lat\":\"54.7186166\",\"geo_lon\":\"135.3131789\",\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":3,\"qc_complete\":0,\"qc_house\":2,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		                    TestCasesError::matcherKhabarSettlement2),
		EAO_1("ЕАО, пос.Приамурский, ул.Ленина, д.1",
		      "[{\"source\":\"ЕАО, пос.Приамурский, ул.Ленина, д.1\",\"result\":\"Еврейская Аобл, Смидовичский р-н, п Приамурский, ул Ленина, д 1\",\"postal_code\":\"679180\",\"country\":\"Россия\",\"region_fias_id\":\"1b507b09-48c9-434f-bf6f-65066211c73e\",\"region_kladr_id\":\"7900000000000\",\"region_with_type\":\"Еврейская Аобл\",\"region_type\":\"Аобл\",\"region_type_full\":\"автономная область\",\"region\":\"Еврейская\",\"area_fias_id\":\"afae4bce-c5fa-4003-bb5e-621b2041cb18\",\"area_kladr_id\":\"7900500000000\",\"area_with_type\":\"Смидовичский р-н\",\"area_type\":\"р-н\",\"area_type_full\":\"район\",\"area\":\"Смидовичский\",\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":\"a090ac0a-b2cf-4c16-90f0-10ba5825ffb2\",\"settlement_kladr_id\":\"7900500001800\",\"settlement_with_type\":\"п Приамурский\",\"settlement_type\":\"п\",\"settlement_type_full\":\"поселок\",\"settlement\":\"Приамурский\",\"street_fias_id\":\"fefa5b6e-351b-444e-94f8-a3c802b60d95\",\"street_kladr_id\":\"79005000018001200\",\"street_with_type\":\"ул Ленина\",\"street_type\":\"ул\",\"street_type_full\":\"улица\",\"street\":\"Ленина\",\"house_fias_id\":\"cf76ce54-0ae9-496a-bd88-a9b7a4369dca\",\"house_kladr_id\":\"7900500001800120001\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"1\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"cf76ce54-0ae9-496a-bd88-a9b7a4369dca\",\"fias_code\":\"79005000018000000120001\",\"fias_level\":\"8\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"7900500001800120001\",\"capital_marker\":\"0\",\"okato\":\"99230565000\",\"oktmo\":\"99630165051\",\"tax_office\":\"7907\",\"tax_office_legal\":\"7907\",\"timezone\":\"UTC+10\",\"geo_lat\":\"48.5234342\",\"geo_lon\":\"134.9128145\",\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":0,\"qc_complete\":0,\"qc_house\":2,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		      TestCasesError::matcherEao1),
		MOSCOW_1("125493, г.Москва, ул.Пулковская, д.4, корп.1, кв.56",
		         "[{\"source\":\"125493, г.Москва, ул.Пулковская, д.4, корп.1, кв.56\",\"result\":\"г Москва, ул Пулковская, д 4 к 1, кв 56\",\"postal_code\":\"125493\",\"country\":\"Россия\",\"region_fias_id\":\"0c5b2444-70a0-4932-980c-b4dc0d3f02b5\",\"region_kladr_id\":\"7700000000000\",\"region_with_type\":\"г Москва\",\"region_type\":\"г\",\"region_type_full\":\"город\",\"region\":\"Москва\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":\"Северный\",\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":\"р-н Головинский\",\"city_district_type\":\"р-н\",\"city_district_type_full\":\"район\",\"city_district\":\"Головинский\",\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":\"a0885c46-2cdc-4bfe-9fed-ae15a5068930\",\"street_kladr_id\":\"77000000000241100\",\"street_with_type\":\"ул Пулковская\",\"street_type\":\"ул\",\"street_type_full\":\"улица\",\"street\":\"Пулковская\",\"house_fias_id\":\"fe3ea672-689e-4b31-8100-90ccd13adcb6\",\"house_kladr_id\":\"7700000000024110005\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"4\",\"block_type\":\"к\",\"block_type_full\":\"корпус\",\"block\":\"1\",\"flat_type\":\"кв\",\"flat_type_full\":\"квартира\",\"flat\":\"56\",\"flat_area\":\"162.7\",\"square_meter_price\":\"273530\",\"flat_price\":\"44503331\",\"postal_box\":null,\"fias_id\":\"fe3ea672-689e-4b31-8100-90ccd13adcb6\",\"fias_code\":\"77000000000000024110005\",\"fias_level\":\"8\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"7700000000024110005\",\"capital_marker\":\"0\",\"okato\":\"45277571000\",\"oktmo\":\"45338000\",\"tax_office\":\"7743\",\"tax_office_legal\":\"7743\",\"timezone\":\"UTC+3\",\"geo_lat\":\"55.8441058\",\"geo_lon\":\"37.4847472\",\"beltway_hit\":\"IN_MKAD\",\"beltway_distance\":null,\"qc_geo\":0,\"qc_complete\":0,\"qc_house\":2,\"qc\":0,\"unparsed_parts\":null,\"metro\":[{\"distance\":0.6,\"line\":\"Замоскворецкая\",\"name\":\"Водный стадион\"},{\"distance\":1.2,\"line\":\"Замоскворецкая\",\"name\":\"Речной вокзал\"},{\"distance\":2.2,\"line\":\"МЦК\",\"name\":\"Балтийская\"}]}]",
		         TestCasesError::matcherMoscow1),
		MOSCOW_2("Москва, Новая площадь, д.12 стр.3",
		         "[{\"source\":\"Москва, Новая площадь, д.12 стр.3\",\"result\":\"г Москва, пл Новая, д 12 стр 3\",\"postal_code\":\"109012\",\"country\":\"Россия\",\"region_fias_id\":\"0c5b2444-70a0-4932-980c-b4dc0d3f02b5\",\"region_kladr_id\":\"7700000000000\",\"region_with_type\":\"г Москва\",\"region_type\":\"г\",\"region_type_full\":\"город\",\"region\":\"Москва\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":\"Центральный\",\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":\"р-н Тверской\",\"city_district_type\":\"р-н\",\"city_district_type_full\":\"район\",\"city_district\":\"Тверской\",\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":\"161df7ef-6705-4a17-8940-e387f379f53c\",\"street_kladr_id\":\"77000000000200900\",\"street_with_type\":\"пл Новая\",\"street_type\":\"пл\",\"street_type_full\":\"площадь\",\"street\":\"Новая\",\"house_fias_id\":\"ec41133b-7824-4b36-9ba9-10d6b8333bf7\",\"house_kladr_id\":\"7700000000020090008\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"12\",\"block_type\":\"стр\",\"block_type_full\":\"строение\",\"block\":\"3\",\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"ec41133b-7824-4b36-9ba9-10d6b8333bf7\",\"fias_code\":\"77000000000000020090008\",\"fias_level\":\"8\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"7700000000020090008\",\"capital_marker\":\"0\",\"okato\":\"45286585000\",\"oktmo\":\"45382000\",\"tax_office\":\"7710\",\"tax_office_legal\":\"7710\",\"timezone\":\"UTC+3\",\"geo_lat\":\"55.7572577\",\"geo_lon\":\"37.6278987\",\"beltway_hit\":\"IN_MKAD\",\"beltway_distance\":null,\"qc_geo\":0,\"qc_complete\":5,\"qc_house\":2,\"qc\":0,\"unparsed_parts\":null,\"metro\":[{\"distance\":0.2,\"line\":\"Калужско-Рижская\",\"name\":\"Китай-город\"},{\"distance\":0.3,\"line\":\"Сокольническая\",\"name\":\"Лубянка\"},{\"distance\":0.4,\"line\":\"Арбатско-Покровская\",\"name\":\"Площадь Революции\"}]}]",
		         TestCasesError::matcherMoscow2),
		MOSCOW_AREA_1("Московская область, г.Балашиха, пос.Агрогородок, ул.Фадеева, д.4А",
		              "[{\"source\":\"Московская область, г.Балашиха, пос.Агрогородок, ул.Фадеева, д.4А\",\"result\":\"Московская обл, г Балашиха, п Агрогородок, ул Фадеева, д 4А\",\"postal_code\":\"143900\",\"country\":\"Россия\",\"region_fias_id\":\"29251dcf-00a1-4e34-98d4-5c47484a36d4\",\"region_kladr_id\":\"5000000000000\",\"region_with_type\":\"Московская обл\",\"region_type\":\"обл\",\"region_type_full\":\"область\",\"region\":\"Московская\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":\"27c5bc66-61bf-4a17-b0cd-ca0eb64192d6\",\"city_kladr_id\":\"5000003600000\",\"city_with_type\":\"г Балашиха\",\"city_type\":\"г\",\"city_type_full\":\"город\",\"city\":\"Балашиха\",\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":\"e96bb618-2966-4296-b371-ec3245bdd682\",\"settlement_kladr_id\":\"5000003600800\",\"settlement_with_type\":\"п Агрогородок\",\"settlement_type\":\"п\",\"settlement_type_full\":\"поселок\",\"settlement\":\"Агрогородок\",\"street_fias_id\":null,\"street_kladr_id\":null,\"street_with_type\":\"ул Фадеева\",\"street_type\":\"ул\",\"street_type_full\":\"улица\",\"street\":\"Фадеева\",\"house_fias_id\":null,\"house_kladr_id\":null,\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"4А\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"e96bb618-2966-4296-b371-ec3245bdd682\",\"fias_code\":\"50000036008000000000000\",\"fias_level\":\"6\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"5000003600800\",\"capital_marker\":\"0\",\"okato\":\"46404000000\",\"oktmo\":\"46704000001\",\"tax_office\":\"5001\",\"tax_office_legal\":\"5001\",\"timezone\":\"UTC+3\",\"geo_lat\":\"55.7433646\",\"geo_lon\":\"38.0457587\",\"beltway_hit\":\"OUT_MKAD\",\"beltway_distance\":\"13\",\"qc_geo\":1,\"qc_complete\":10,\"qc_house\":10,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		              TestCasesError::matcherMoscowArea1),
		MOSCOW_AREA_2("Балашиха, Носовихинское шоссе, вл4 лит П",
		              "[{\"source\":\"Балашиха, Носовихинское шоссе, вл4 лит П\",\"result\":\"Московская обл, г Балашиха, мкр Керамик, ш Носовихинское, д 4П\",\"postal_code\":\"143983\",\"country\":\"Россия\",\"region_fias_id\":\"29251dcf-00a1-4e34-98d4-5c47484a36d4\",\"region_kladr_id\":\"5000000000000\",\"region_with_type\":\"Московская обл\",\"region_type\":\"обл\",\"region_type_full\":\"область\",\"region\":\"Московская\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":\"27c5bc66-61bf-4a17-b0cd-ca0eb64192d6\",\"city_kladr_id\":\"5000003600000\",\"city_with_type\":\"г Балашиха\",\"city_type\":\"г\",\"city_type_full\":\"город\",\"city\":\"Балашиха\",\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":\"456da635-be39-4308-ac95-ce1d0b97673e\",\"settlement_kladr_id\":\"5000003605300\",\"settlement_with_type\":\"мкр Керамик\",\"settlement_type\":\"мкр\",\"settlement_type_full\":\"микрорайон\",\"settlement\":\"Керамик\",\"street_fias_id\":\"4f4f9e52-a570-449b-8b24-e23b86887f12\",\"street_kladr_id\":\"50000036053000100\",\"street_with_type\":\"ш Носовихинское\",\"street_type\":\"ш\",\"street_type_full\":\"шоссе\",\"street\":\"Носовихинское\",\"house_fias_id\":null,\"house_kladr_id\":null,\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"4П\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"4f4f9e52-a570-449b-8b24-e23b86887f12\",\"fias_code\":\"50000036053000000010000\",\"fias_level\":\"7\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"50000036053000100\",\"capital_marker\":\"0\",\"okato\":\"46404000000\",\"oktmo\":\"46704000001\",\"tax_office\":\"5012\",\"tax_office_legal\":\"5012\",\"timezone\":\"UTC+3\",\"geo_lat\":\"55.7502268\",\"geo_lon\":\"37.97459\",\"beltway_hit\":\"OUT_MKAD\",\"beltway_distance\":\"9\",\"qc_geo\":1,\"qc_complete\":9,\"qc_house\":10,\"qc\":1,\"unparsed_parts\":\"ВЛ\",\"metro\":null}]",
		              TestCasesError::matcherMoscowArea2),
		SPB_1("Россия, Санкт-Петербург, ул.Восстания, д.1", "[{\"source\":\"Россия, Санкт-Петербург, ул.Восстания, д.1\",\"result\":\"г Санкт-Петербург, ул Восстания, д 1\",\"postal_code\":\"191036\",\"country\":\"Россия\",\"region_fias_id\":\"c2deb16a-0330-4f05-821f-1d09c93331e6\",\"region_kladr_id\":\"7800000000000\",\"region_with_type\":\"г Санкт-Петербург\",\"region_type\":\"г\",\"region_type_full\":\"город\",\"region\":\"Санкт-Петербург\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":\"р-н Центральный\",\"city_district_type\":\"р-н\",\"city_district_type_full\":\"район\",\"city_district\":\"Центральный\",\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":\"77ce3c92-e903-497e-bdfa-4193c83c03f8\",\"street_kladr_id\":\"78000000000026600\",\"street_with_type\":\"ул Восстания\",\"street_type\":\"ул\",\"street_type_full\":\"улица\",\"street\":\"Восстания\",\"house_fias_id\":\"3166af83-33f1-4e63-a239-04fb8d93b996\",\"house_kladr_id\":\"7800000000002660060\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"1\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":\"155172\",\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"3166af83-33f1-4e63-a239-04fb8d93b996\",\"fias_code\":\"78000000000000002660060\",\"fias_level\":\"8\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"7800000000002660060\",\"capital_marker\":\"0\",\"okato\":\"40298564000\",\"oktmo\":\"40911000\",\"tax_office\":\"7842\",\"tax_office_legal\":\"7842\",\"timezone\":\"UTC+3\",\"geo_lat\":\"59.9321789\",\"geo_lon\":\"30.3604219\",\"beltway_hit\":\"IN_KAD\",\"beltway_distance\":null,\"qc_geo\":1,\"qc_complete\":5,\"qc_house\":2,\"qc\":0,\"unparsed_parts\":null,\"metro\":[{\"distance\":0.2,\"line\":\"Кировско-Выборгская\",\"name\":\"Площадь Восстания\"},{\"distance\":0.3,\"line\":\"Невско-Василеостровская\",\"name\":\"Маяковская\"},{\"distance\":0.9,\"line\":\"Кировско-Выборгская\",\"name\":\"Владимирская\"}]}]",
		      TestCasesError::matcherSpb1),
		NOVOSIB_1("Новосибирск, ул.Новогодняя, д.12, кв.5",
		          "[{\"source\":\"Новосибирск, ул.Новогодняя, д.12, кв.5\",\"result\":\"г Новосибирск, ул Новогодняя, д 12, кв 5\",\"postal_code\":\"630064\",\"country\":\"Россия\",\"region_fias_id\":\"1ac46b49-3209-4814-b7bf-a509ea1aecd9\",\"region_kladr_id\":\"5400000000000\",\"region_with_type\":\"Новосибирская обл\",\"region_type\":\"обл\",\"region_type_full\":\"область\",\"region\":\"Новосибирская\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":\"8dea00e3-9aab-4d8e-887c-ef2aaa546456\",\"city_kladr_id\":\"5400000100000\",\"city_with_type\":\"г Новосибирск\",\"city_type\":\"г\",\"city_type_full\":\"город\",\"city\":\"Новосибирск\",\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":\"р-н Кировский\",\"city_district_type\":\"р-н\",\"city_district_type_full\":\"район\",\"city_district\":\"Кировский\",\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":\"80ce90aa-4d23-4207-b16d-62575f44c5e5\",\"street_kladr_id\":\"54000001000087500\",\"street_with_type\":\"ул Новогодняя\",\"street_type\":\"ул\",\"street_type_full\":\"улица\",\"street\":\"Новогодняя\",\"house_fias_id\":\"7cb96b36-b00f-4e69-afa1-088a129cdf75\",\"house_kladr_id\":\"5400000100008750027\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"12\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":\"кв\",\"flat_type_full\":\"квартира\",\"flat\":\"5\",\"flat_area\":\"30.6\",\"square_meter_price\":\"56941\",\"flat_price\":\"1742395\",\"postal_box\":null,\"fias_id\":\"7cb96b36-b00f-4e69-afa1-088a129cdf75\",\"fias_code\":\"54000001000000008750027\",\"fias_level\":\"8\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"5400000100008750027\",\"capital_marker\":\"2\",\"okato\":\"50401374000\",\"oktmo\":\"50701000001\",\"tax_office\":\"5403\",\"tax_office_legal\":\"5403\",\"timezone\":\"UTC+7\",\"geo_lat\":\"54.9828326\",\"geo_lon\":\"82.9039741\",\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":0,\"qc_complete\":0,\"qc_house\":2,\"qc\":0,\"unparsed_parts\":null,\"metro\":[{\"distance\":0.7,\"line\":\"Ленинская\",\"name\":\"Площадь Маркса\"},{\"distance\":0.7,\"line\":\"Ленинская\",\"name\":\"Студенческая\"},{\"distance\":3.6,\"line\":\"Ленинская\",\"name\":\"Речной вокзал\"}]}]",
		          TestCasesError::matcherNovosib1),
		POSTBOX_1("Анадырь, а/я 123", "[{\"source\":\"Анадырь, а/я 123\",\"result\":\"г Анадырь, а/я 123\",\"postal_code\":null,\"country\":\"Россия\",\"region_fias_id\":\"f136159b-404a-4f1f-8d8d-d169e1374d5c\",\"region_kladr_id\":\"8700000000000\",\"region_with_type\":\"Чукотский АО\",\"region_type\":\"АО\",\"region_type_full\":\"автономный округ\",\"region\":\"Чукотский\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":\"7fad3a21-06b4-4af3-9657-bf1521714952\",\"city_kladr_id\":\"8700000100000\",\"city_with_type\":\"г Анадырь\",\"city_type\":\"г\",\"city_type_full\":\"город\",\"city\":\"Анадырь\",\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":null,\"street_kladr_id\":null,\"street_with_type\":null,\"street_type\":null,\"street_type_full\":null,\"street\":null,\"house_fias_id\":null,\"house_kladr_id\":null,\"house_type\":null,\"house_type_full\":null,\"house\":null,\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":\"123\",\"fias_id\":\"7fad3a21-06b4-4af3-9657-bf1521714952\",\"fias_code\":\"87000001000000000000000\",\"fias_level\":\"4\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"8700000100000\",\"capital_marker\":\"2\",\"okato\":\"77401000000\",\"oktmo\":\"77701000\",\"tax_office\":\"8709\",\"tax_office_legal\":\"8709\",\"timezone\":\"UTC+12\",\"geo_lat\":\"64.7313924\",\"geo_lon\":\"177.5015421\",\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":4,\"qc_complete\":8,\"qc_house\":10,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		          TestCasesError::matcherPostbox1),
		AMBIGIOUS_1("Москва, Тверская-Ямская, 5", "[{\"source\":\"Москва, Тверская-Ямская, 5\",\"result\":\"г Москва, ул Тверская-Ямская 1-я, д 5\",\"postal_code\":\"125047\",\"country\":\"Россия\",\"region_fias_id\":\"0c5b2444-70a0-4932-980c-b4dc0d3f02b5\",\"region_kladr_id\":\"7700000000000\",\"region_with_type\":\"г Москва\",\"region_type\":\"г\",\"region_type_full\":\"город\",\"region\":\"Москва\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":\"Центральный\",\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":\"р-н Тверской\",\"city_district_type\":\"р-н\",\"city_district_type_full\":\"район\",\"city_district\":\"Тверской\",\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":\"94d0cf51-2820-4409-bbd7-4a7d36f2922b\",\"street_kladr_id\":\"77000000000287900\",\"street_with_type\":\"ул Тверская-Ямская 1-я\",\"street_type\":\"ул\",\"street_type_full\":\"улица\",\"street\":\"Тверская-Ямская 1-я\",\"house_fias_id\":\"6cddf0f2-6baa-43b3-bfc4-d75b3c7fd97f\",\"house_kladr_id\":\"7700000000028790006\",\"house_type\":\"д\",\"house_type_full\":\"дом\",\"house\":\"5\",\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"6cddf0f2-6baa-43b3-bfc4-d75b3c7fd97f\",\"fias_code\":\"77000000000000028790006\",\"fias_level\":\"8\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"7700000000028790006\",\"capital_marker\":\"0\",\"okato\":\"45286585000\",\"oktmo\":\"45382000\",\"tax_office\":\"7710\",\"tax_office_legal\":\"7710\",\"timezone\":\"UTC+3\",\"geo_lat\":\"55.7709247\",\"geo_lon\":\"37.5933976\",\"beltway_hit\":\"IN_MKAD\",\"beltway_distance\":null,\"qc_geo\":0,\"qc_complete\":9,\"qc_house\":2,\"qc\":3,\"unparsed_parts\":null,\"metro\":[{\"distance\":0.2,\"line\":\"Замоскворецкая\",\"name\":\"Маяковская\"},{\"distance\":0.8,\"line\":\"Кольцевая\",\"name\":\"Белорусская\"},{\"distance\":0.9,\"line\":\"Замоскворецкая\",\"name\":\"Тверская\"}]}]",
		            TestCasesError::matcherAmbigious1),
		INCOMPLETE_1("Россия, Рязанская область", "[{\"source\":\"Россия, Рязанская область\",\"result\":\"Рязанская обл\",\"postal_code\":\"390000\",\"country\":\"Россия\",\"region_fias_id\":\"963073ee-4dfc-48bd-9a70-d2dfc6bd1f31\",\"region_kladr_id\":\"6200000000000\",\"region_with_type\":\"Рязанская обл\",\"region_type\":\"обл\",\"region_type_full\":\"область\",\"region\":\"Рязанская\",\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":null,\"street_kladr_id\":null,\"street_with_type\":null,\"street_type\":null,\"street_type_full\":null,\"street\":null,\"house_fias_id\":null,\"house_kladr_id\":null,\"house_type\":null,\"house_type_full\":null,\"house\":null,\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":\"963073ee-4dfc-48bd-9a70-d2dfc6bd1f31\",\"fias_code\":\"62000000000000000000000\",\"fias_level\":\"1\",\"fias_actuality_state\":\"0\",\"kladr_id\":\"6200000000000\",\"capital_marker\":\"0\",\"okato\":\"61000000000\",\"oktmo\":null,\"tax_office\":\"6200\",\"tax_office_legal\":\"6200\",\"timezone\":\"UTC+3\",\"geo_lat\":null,\"geo_lon\":null,\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":5,\"qc_complete\":2,\"qc_house\":10,\"qc\":0,\"unparsed_parts\":null,\"metro\":null}]",
		             TestCasesError::matcherIncomplete1),
		FOREIGN_1("170 West Tasman Drive, San Jose, CA 95134, USA",
		          "[{\"source\":\"170 West Tasman Drive, San Jose, CA 95134, USA\",\"result\":\"Соединенные Штаты\",\"postal_code\":null,\"country\":\"Соединенные Штаты\",\"region_fias_id\":null,\"region_kladr_id\":null,\"region_with_type\":null,\"region_type\":null,\"region_type_full\":null,\"region\":null,\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":null,\"street_kladr_id\":null,\"street_with_type\":null,\"street_type\":null,\"street_type_full\":null,\"street\":null,\"house_fias_id\":null,\"house_kladr_id\":null,\"house_type\":null,\"house_type_full\":null,\"house\":null,\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":null,\"fias_code\":null,\"fias_level\":\"-1\",\"fias_actuality_state\":\"0\",\"kladr_id\":null,\"capital_marker\":\"0\",\"okato\":null,\"oktmo\":null,\"tax_office\":null,\"tax_office_legal\":null,\"timezone\":null,\"geo_lat\":null,\"geo_lon\":null,\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":5,\"qc_complete\":7,\"qc_house\":10,\"qc\":1,\"unparsed_parts\":\"ВЕСТ, ТАСМАН, ДРИВЕ, САН, ЕСЕ, КА, 95134, 170\",\"metro\":null}]",
		          TestCasesError::matcherForeign1),
		UNPARSEABLE_1("qwe",
		              "[{\"source\":\"qwe\",\"result\":null,\"postal_code\":null,\"country\":null,\"region_fias_id\":null,\"region_kladr_id\":null,\"region_with_type\":null,\"region_type\":null,\"region_type_full\":null,\"region\":null,\"area_fias_id\":null,\"area_kladr_id\":null,\"area_with_type\":null,\"area_type\":null,\"area_type_full\":null,\"area\":null,\"city_fias_id\":null,\"city_kladr_id\":null,\"city_with_type\":null,\"city_type\":null,\"city_type_full\":null,\"city\":null,\"city_area\":null,\"city_district_fias_id\":null,\"city_district_kladr_id\":null,\"city_district_with_type\":null,\"city_district_type\":null,\"city_district_type_full\":null,\"city_district\":null,\"settlement_fias_id\":null,\"settlement_kladr_id\":null,\"settlement_with_type\":null,\"settlement_type\":null,\"settlement_type_full\":null,\"settlement\":null,\"street_fias_id\":null,\"street_kladr_id\":null,\"street_with_type\":null,\"street_type\":null,\"street_type_full\":null,\"street\":null,\"house_fias_id\":null,\"house_kladr_id\":null,\"house_type\":null,\"house_type_full\":null,\"house\":null,\"block_type\":null,\"block_type_full\":null,\"block\":null,\"flat_type\":null,\"flat_type_full\":null,\"flat\":null,\"flat_area\":null,\"square_meter_price\":null,\"flat_price\":null,\"postal_box\":null,\"fias_id\":null,\"fias_code\":null,\"fias_level\":\"-1\",\"fias_actuality_state\":\"0\",\"kladr_id\":null,\"capital_marker\":\"0\",\"okato\":null,\"oktmo\":null,\"tax_office\":null,\"tax_office_legal\":null,\"timezone\":null,\"geo_lat\":null,\"geo_lon\":null,\"beltway_hit\":null,\"beltway_distance\":null,\"qc_geo\":5,\"qc_complete\":1,\"qc_house\":10,\"qc\":1,\"unparsed_parts\":\"КВЕ\",\"metro\":null}]",
		              TestCasesError::matcherUnparseable1);
*/

		private final Object argument;
		private final String requestBody;
		private final String message;
		private final HttpStatus responseStatus;
		private final String responseBody;
		private final Function<Object, Matcher<DaDataClientException>> matcher;

		SampleErrorAddresses(final Object argument, final String requestBody, final String message, final HttpStatus responseStatus, final String responseBody, final Function<Object, Matcher<DaDataClientException>> matcher) {
			this.argument = argument;
			this.requestBody = requestBody;
			this.message = message;
			this.responseStatus = responseStatus;
			this.responseBody = responseBody;
			this.matcher = matcher;
		}

		public Object getArgument() {
			return argument;
		}

		public String getRequestBody() {
			return requestBody;
		}

		public String getMessage() {
			return message;
		}

		public HttpStatus getResponseStatus() {
			return responseStatus;
		}

		public String getResponseBody() {
			return responseBody;
		}

		public Matcher<DaDataClientException> getMatcher() {
			return matcher != null ? matcher.apply(argument) : nullValue(DaDataClientException.class);
		}
	}

	// -----------------------------------------------------------------------------------------------------------------

	// empty address array
	private static Matcher<DaDataClientException> matcherEmptyArray(final Object o) {
		return allOf(hasProperty("httpStatusCode", is(400)),
		             hasProperty("httpStatusText", is(equalToIgnoringCase("BAD REQUEST"))),
		             hasProperty("apiErrorCode", is(BAD_REQUEST_FORMAT)),
		             hasProperty("apiErrorMessage", notNullValue(APIErrorMessage.class)),
		             hasProperty("apiErrorMessage", hasProperty("detail", is("Bad request. Use non empty list."))),
		             hasProperty("fatal", is(true)));
	}

	// TODO implement other cases

	// =================================================================================================================
}
